name: Workflow Main

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-prod:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ENVIRONMENT_NAME: production
    secrets: inherit
