name: Workflow Dev

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deploy-test:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ENVIRONMENT_NAME: development
    secrets: inherit
